### ISSUE TITLE
AnimationControllers not disposed.  

### ISSUE THREAD

**Issue by UnilGandhi** [ojasjain24/neon_widgets_flutter#3]
**The following assertion was thrown while notifying status listeners for AnimationController:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4397 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.**

Started getting this exception in my logs after this plugin was implemented. What I understood from the error and searching the solutions online, is that the animation controllers used for the flickering widgets are not disposed off and hence this exception is thrown.
It doesn't crash the app or anything but a fix would be better.

**Comment by ojasjain24** [comment]
Hi, Can you please share the screenshot of your logs? and also please provide the list of the widgets, you used from the package.

Thanks.

**Comment by UnilGandhi** [comment]
Hi, I have used the oFlickerNeonPoint widget from the package. I thing the Flicker widgets must be having the issue given the animation. 
Attaching screenshot of the error log.

![image](https://user-images.githubusercontent.com/16099618/174012593-76c7b8bf-8f17-4651-996f-6653bbbeaa03.png)

Thanks.

**Comment by ojasjain24** [comment]
Fixed
